create extension if not exists pgcrypto;

create table if not exists public.orders (
  id text primary key,
  items jsonb not null default '[]'::jsonb,
  total integer not null,
  subtotal integer not null default 0,
  discount integer not null default 0,
  shipping integer not null default 0,
  coupon text not null default '',
  customer jsonb not null default '{}'::jsonb,
  payment_method text not null,
  status text not null,
  paid boolean not null default false,
  payment_claimed boolean not null default false,
  tracking text not null default '',
  session_id text not null default '',
  stripe_session text not null default '',
  user_id text not null default '',
  access_token text not null default '',
  resources_reserved boolean not null default false,
  created_at bigint not null,
  updated_at bigint not null
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  session_id text not null,
  sender text not null,
  text text not null,
  at bigint not null
);

create table if not exists public.users (
  id text primary key,
  email text not null unique,
  name text not null default '',
  salt text not null,
  hash text not null,
  role text not null default 'user',
  created_at bigint not null
);

create table if not exists public.auth_tokens (
  token text primary key,
  user_id text not null,
  created_at bigint not null,
  expires_at bigint not null
);

create table if not exists public.products (
  id text primary key,
  name text not null,
  tag text not null default '',
  price integer not null,
  short text not null default '',
  description text not null default '',
  specs jsonb not null default '{}'::jsonb,
  segment text not null default 'agri',
  extra jsonb not null default '{}'::jsonb,
  icon text not null default 'pod',
  image text not null default '',
  video text not null default '',
  images jsonb not null default '[]'::jsonb,
  model text not null default '',
  stock integer not null default 0,
  active boolean not null default true,
  sort integer not null default 0,
  created_at bigint not null
);

create table if not exists public.settings (
  key text primary key,
  value text not null default ''
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  product_id text not null,
  user_id text not null,
  name text not null default '',
  rating integer not null,
  comment text not null default '',
  created_at bigint not null
);

create table if not exists public.coupons (
  code text primary key,
  type text not null,
  value integer not null,
  min_total integer not null default 0,
  max_uses integer not null default 0,
  used integer not null default 0,
  active boolean not null default true,
  expires_at bigint not null default 0,
  created_at bigint not null
);

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  line_id text not null default '',
  province text not null default '',
  crop text not null default '',
  stage text not null default '',
  area_rai text not null default '',
  problem text not null default '',
  source text not null default '',
  landing_page text not null default '',
  utm_source text not null default '',
  utm_medium text not null default '',
  utm_campaign text not null default '',
  note text not null default '',
  status text not null default 'new',
  created_at bigint not null,
  updated_at bigint not null
);

create table if not exists public.articles (
  id text primary key,
  title text not null,
  cover text not null default '',
  excerpt text not null default '',
  body text not null default '',
  published boolean not null default true,
  created_at bigint not null
);

create table if not exists public.community_posts (
  store_id text not null default 'store_main',
  id text primary key,
  user_id text not null default '',
  author_name text not null default 'สมาชิก',
  author_avatar text not null default '',
  author_role text not null default 'member',
  caption text not null default '',
  media jsonb not null default '[]'::jsonb,
  hashtags jsonb not null default '[]'::jsonb,
  article_id text not null default '',
  product_ids jsonb not null default '[]'::jsonb,
  status text not null default 'pending',
  pinned boolean not null default false,
  created_at bigint not null default 0,
  updated_at bigint not null default 0
);

create table if not exists public.community_comments (
  store_id text not null default 'store_main',
  id text primary key,
  post_id text not null references public.community_posts(id) on delete cascade,
  user_id text not null default '',
  author_name text not null default 'สมาชิก',
  text text not null default '',
  status text not null default 'approved',
  created_at bigint not null default 0
);

create table if not exists public.community_reactions (
  store_id text not null default 'store_main',
  post_id text not null references public.community_posts(id) on delete cascade,
  user_id text not null,
  type text not null default 'like',
  created_at bigint not null default 0,
  primary key (post_id, user_id, type)
);

create table if not exists public.community_saves (
  store_id text not null default 'store_main',
  post_id text not null references public.community_posts(id) on delete cascade,
  user_id text not null,
  created_at bigint not null default 0,
  primary key (post_id, user_id)
);

create table if not exists public.community_stories (
  store_id text not null default 'store_main',
  id text primary key,
  post_id text not null default '',
  author_name text not null default 'Community',
  title text not null default '',
  media text not null default '',
  caption text not null default '',
  status text not null default 'approved',
  created_at bigint not null default 0,
  expires_at bigint not null default 0
);

create index if not exists idx_orders_created_at on public.orders (created_at desc);
create index if not exists idx_orders_user_id on public.orders (user_id);
create unique index if not exists idx_orders_access_token on public.orders (access_token);
create index if not exists idx_messages_session_id on public.messages (session_id);
create index if not exists idx_products_active_sort on public.products (active, sort, created_at);
create index if not exists idx_reviews_product_id on public.reviews (product_id, created_at desc);
create index if not exists idx_leads_created_at on public.leads (created_at desc);
create index if not exists idx_articles_published_created_at on public.articles (published, created_at desc);
create index if not exists idx_community_posts_store_status_created on public.community_posts (store_id, status, pinned desc, created_at desc);
create index if not exists idx_community_comments_store_post_created on public.community_comments (store_id, post_id, status, created_at);
create index if not exists idx_community_reactions_store_post on public.community_reactions (store_id, post_id, type);
create index if not exists idx_community_saves_store_post on public.community_saves (store_id, post_id);
create index if not exists idx_community_stories_store_expiry on public.community_stories (store_id, status, expires_at desc, created_at desc);

create or replace function public.reserve_order_resources(
  p_items jsonb default '[]'::jsonb,
  p_coupon text default ''
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  item jsonb;
  v_id text;
  v_qty integer;
begin
  if jsonb_typeof(coalesce(p_items, '[]'::jsonb)) <> 'array' then
    raise exception 'รายการสินค้าไม่ถูกต้อง';
  end if;

  for item in select * from jsonb_array_elements(coalesce(p_items, '[]'::jsonb))
  loop
    v_id := btrim(coalesce(item->>'id', ''));
    v_qty := greatest(1, coalesce((item->>'qty')::integer, 0));
    if v_id = '' then
      raise exception 'พบรายการสินค้าที่ไม่มีรหัส';
    end if;

    update public.products
       set stock = stock - v_qty
     where id = v_id
       and stock >= v_qty;
    if not found then
      raise exception 'สินค้า % คงเหลือไม่พอ', v_id;
    end if;
  end loop;

  if btrim(coalesce(p_coupon, '')) <> '' then
    update public.coupons
       set used = used + 1
     where code = upper(btrim(p_coupon))
       and active = true
       and (expires_at = 0 or expires_at > (extract(epoch from clock_timestamp()) * 1000)::bigint)
       and (max_uses = 0 or used < max_uses);
    if not found then
      raise exception 'คูปอง % ใช้งานไม่ได้แล้ว', upper(btrim(p_coupon));
    end if;
  end if;
end;
$$;

create or replace function public.release_order_resources(
  p_items jsonb default '[]'::jsonb,
  p_coupon text default ''
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  item jsonb;
  v_id text;
  v_qty integer;
begin
  if jsonb_typeof(coalesce(p_items, '[]'::jsonb)) <> 'array' then
    raise exception 'รายการสินค้าไม่ถูกต้อง';
  end if;

  for item in select * from jsonb_array_elements(coalesce(p_items, '[]'::jsonb))
  loop
    v_id := btrim(coalesce(item->>'id', ''));
    v_qty := greatest(1, coalesce((item->>'qty')::integer, 0));
    if v_id = '' then
      continue;
    end if;
    update public.products
       set stock = stock + v_qty
     where id = v_id;
  end loop;

  if btrim(coalesce(p_coupon, '')) <> '' then
    update public.coupons
       set used = greatest(0, used - 1)
     where code = upper(btrim(p_coupon));
  end if;
end;
$$;

comment on table public.orders is 'Migrated from local SQLite store';
comment on table public.settings is 'CMS/site settings key-value store';
-- 009: ย้าย chat inbox meta + LINE webhook idempotency/audit จาก settings blob ไปตารางจริง
-- แก้ปัญหา read-modify-write race บน serverless (หลาย instance เขียนทับกัน) และลด latency ต่อข้อความ
-- DDL อย่างเดียว — การย้ายข้อมูลจาก blob เดิม (SITE_CHAT_INBOX_META) โค้ดเว็บทำให้อัตโนมัติตอน boot แรก

create table if not exists public.chat_session_meta (
  session_id text primary key,
  meta jsonb not null default '{}'::jsonb,
  updated_at bigint not null default 0
);
alter table public.chat_session_meta enable row level security;

create table if not exists public.line_webhook_events (
  event_key text primary key,
  at bigint not null default 0
);
alter table public.line_webhook_events enable row level security;

create table if not exists public.line_webhook_audits (
  id text primary key,
  at bigint not null default 0,
  event_key text not null default '',
  event_type text not null default '',
  source_key text not null default '',
  message_type text not null default '',
  text_preview text not null default '',
  result text not null default '',
  duration_ms bigint not null default 0,
  error text not null default '',
  note text not null default ''
);
create index if not exists idx_line_webhook_audits_at on public.line_webhook_audits (at desc);
alter table public.line_webhook_audits enable row level security;
alter table public.community_posts enable row level security;
alter table public.community_comments enable row level security;
alter table public.community_reactions enable row level security;
alter table public.community_saves enable row level security;
alter table public.community_stories enable row level security;
