create table if not exists public.orders (
  id text primary key,
  items jsonb not null default '[]'::jsonb,
  total integer not null,
  subtotal integer not null default 0,
  discount integer not null default 0,
  shipping integer not null default 0,
  coupon text not null default '',
  customer jsonb not null default '{}'::jsonb,
  payment_method text not null,
  status text not null,
  paid boolean not null default false,
  payment_claimed boolean not null default false,
  tracking text not null default '',
  session_id text not null default '',
  stripe_session text not null default '',
  user_id text not null default '',
  created_at bigint not null,
  updated_at bigint not null
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  session_id text not null,
  sender text not null,
  text text not null,
  at bigint not null
);

create table if not exists public.users (
  id text primary key,
  email text not null unique,
  name text not null default '',
  salt text not null,
  hash text not null,
  role text not null default 'user',
  created_at bigint not null
);

create table if not exists public.auth_tokens (
  token text primary key,
  user_id text not null,
  created_at bigint not null,
  expires_at bigint not null
);

create table if not exists public.products (
  id text primary key,
  name text not null,
  tag text not null default '',
  price integer not null,
  short text not null default '',
  description text not null default '',
  specs jsonb not null default '{}'::jsonb,
  segment text not null default 'agri',
  extra jsonb not null default '{}'::jsonb,
  icon text not null default 'pod',
  image text not null default '',
  video text not null default '',
  images jsonb not null default '[]'::jsonb,
  model text not null default '',
  stock integer not null default 0,
  active boolean not null default true,
  sort integer not null default 0,
  created_at bigint not null
);

create table if not exists public.settings (
  key text primary key,
  value text not null default ''
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  product_id text not null,
  user_id text not null,
  name text not null default '',
  rating integer not null,
  comment text not null default '',
  created_at bigint not null
);

create table if not exists public.coupons (
  code text primary key,
  type text not null,
  value integer not null,
  min_total integer not null default 0,
  max_uses integer not null default 0,
  used integer not null default 0,
  active boolean not null default true,
  expires_at bigint not null default 0,
  created_at bigint not null
);

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  line_id text not null default '',
  province text not null default '',
  crop text not null default '',
  stage text not null default '',
  area_rai text not null default '',
  problem text not null default '',
  source text not null default '',
  landing_page text not null default '',
  utm_source text not null default '',
  utm_medium text not null default '',
  utm_campaign text not null default '',
  note text not null default '',
  status text not null default 'new',
  created_at bigint not null,
  updated_at bigint not null
);

create table if not exists public.articles (
  id text primary key,
  title text not null,
  cover text not null default '',
  excerpt text not null default '',
  body text not null default '',
  published boolean not null default true,
  created_at bigint not null
);

create index if not exists idx_orders_created_at on public.orders (created_at desc);
create index if not exists idx_orders_user_id on public.orders (user_id);
create index if not exists idx_messages_session_id on public.messages (session_id);
create index if not exists idx_products_active_sort on public.products (active, sort, created_at);
create index if not exists idx_reviews_product_id on public.reviews (product_id, created_at desc);
create index if not exists idx_leads_created_at on public.leads (created_at desc);
create index if not exists idx_articles_published_created_at on public.articles (published, created_at desc);

comment on table public.orders is 'Migrated from local SQLite store';
comment on table public.settings is 'CMS/site settings key-value store';
